### ISSUE TITLE
Netty简洁版服务器练手

### ISSUE THREAD

**Issue by yourgentlesmile** [yourgentlesmile/Netty-Exercise#1]
需要实现的功能：
1、当一个客户端连接上来，回显一个欢迎消息，并告诉他，他是目前第几个连接，还有谁已连接服务器。
2、当一个客户端发送消息到服务器后，将此消息广播给所有已连接的客户端
接收的数据包格式：

magic-block     包含字符     PFLO | version | username length   (int) | username | msg length     (long) | msg body | method type
-- | -- | -- | -- | -- | -- | --
4byte | 1byte | 4byte |   | 8byte |  |  1byte |

服务端发送的数据包暂无格式，直接String转byte发送即可

**Comment by yourgentlesmile** [comment]
# 相关commit
https://github.com/yourgentlesmile/Netty-Exercise/commit/30051202c6cf2949b0fb42370268bbd266774f9b  
https://github.com/yourgentlesmile/Netty-Exercise/commit/567f3fdf22f20a3274d86a11dbd6cbd1032b18ed  
https://github.com/yourgentlesmile/Netty-Exercise/commit/aefb090b3ed6f843d79e1767f3f178ad467dbb6a
Author : @chanToTo 
## 小问题(非技术点)
1、magicBlock未读取完整
https://github.com/yourgentlesmile/Netty-Exercise/blob/aefb090b3ed6f843d79e1767f3f178ad467dbb6a/src/main/java/group/collaborators/csf/server/EchoServerHandler.java#L29
2、预留了8byte存long类型的时候，就应该使用writeLong这个方法(我代码里好像也没用对- -)
https://github.com/yourgentlesmile/Netty-Exercise/blob/aefb090b3ed6f843d79e1767f3f178ad467dbb6a/src/main/java/group/collaborators/csf/client/EchoClient.java#L73
3、数据包组装的时候，少了version字节，和用户名数据与消息体数据顺序反了
https://github.com/yourgentlesmile/Netty-Exercise/blob/aefb090b3ed6f843d79e1767f3f178ad467dbb6a/src/main/java/group/collaborators/csf/client/EchoClient.java#L81-L85

## 可记录点(技术bug)
1、当我发送一条消息后，想再次发送的时候，会报如下错误，该如何修复
```java
九月 23, 2019 1:12:59 下午 io.netty.util.ReferenceCountUtil safeRelease
警告: Failed to release a message: UnpooledHeapByteBuf(freed)
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:74)
	at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:138)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:100)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88)
	at io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:113)
	at io.netty.buffer.CompositeByteBuf.addComponents0(CompositeByteBuf.java:368)
	at io.netty.buffer.CompositeByteBuf.addComponents(CompositeByteBuf.java:236)
	at group.collaborators.csf.client.EchoClient.sendMessage(EchoClient.java:82)
	at group.collaborators.csf.client.EchoClient.start(EchoClient.java:55)
	at group.collaborators.csf.client.EchoClient.main(EchoClient.java:41)
```

## 疑惑点 
这里if的两个分支都一样，是有什么考量么？另外这里使用retain我没太清楚，emmm，有空讲解一下
https://github.com/yourgentlesmile/Netty-Exercise/blob/aefb090b3ed6f843d79e1767f3f178ad467dbb6a/src/main/java/group/collaborators/csf/server/EchoServerHandler.java#L34-L44

## 可优化点
这块逻辑可以理解，但是，考虑一下是不是可以更简洁一点
https://github.com/yourgentlesmile/Netty-Exercise/blob/aefb090b3ed6f843d79e1767f3f178ad467dbb6a/src/main/java/group/collaborators/csf/server/EchoServerHandler.java#L63-L78
> **建议**
1、超长代码建议换行，不要超过120个字符
https://github.com/yourgentlesmile/Netty-Exercise/blob/aefb090b3ed6f843d79e1767f3f178ad467dbb6a/src/main/java/group/collaborators/csf/server/EchoServer.java#L35
